// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrzqozbqosuwjbsxcmqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyenFvemJxb3N1d2pic3hjbXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjE3NjQsImV4cCI6MjA3MjE5Nzc2NH0.vUEKT6yE5GBsphPNwcpeHcl53VNrGFT_khThhwqSqfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});